### ISSUE TITLE
Create Listing Page

### ISSUE THREAD

**Issue by briannapoulos** [crosscutio/dhis2-crosscut-app#1]
- [x] Retrieve and display a list of DHIS2-compatible catchment jobs
- [x] Include four columns: Name, Date Created, Status, and Publish to DHIS2

<img width="1123" alt="Screen Shot 2022-03-25 at 1 29 09 PM" src="https://user-images.githubusercontent.com/13878539/160171676-369f424c-d5b8-4425-a95e-2b79d300a6cc.png">

**Comment by luongt13** [comment]
https://www.youtube.com/watch?v=HEE1QapS1Qw&ab_channel=KennethKoker
