### ISSUE TITLE
Enable Publishing

### ISSUE THREAD

**Issue by briannapoulos** [crosscutio/dhis2-crosscut-app#3]
- [x] When the user clicks `Publish`, push the catchment to DHIS2.
 * Allow them to connect the catchment job with the organizational units the job is associated with by creating an attributeValue with the same name as the catchment job and adding this attribute to each organizational unit. For each organizational unit, the value of the attribute should be the GeoJSON polygon of its corresponding catchment.
- [x] Prepend `Crosscut` to the name of the catchment area.
- [x] Change the status to `Publishing` and then to `Published` while push is in-progress & then complete.

**Comment by luongt13** [comment]
when the user clicks `publish`, api call to post to create `attributeValue` with the same name as the catchment + prepend  `crosscut` then add the created `attributeValue` corresponding GeoJSON to each org unit. 
- what's the endpoint to create an `attributeValue` and what should be passed? 
- is there a separate endpoint that adds the created `attributeValue` to each org unit? If so, what's the endpoint?
