### ISSUE TITLE
Update Crosscut logo for DHIS2

### ISSUE THREAD

**Issue by EmmanuelKoh** [crosscutio/dhis2-crosscut-app#66]

**Comment by coitemanuel** [comment]
Currently, for Crosscut, Brianna Poulos has an account at the 
DHIS2 App Hub. Once Brianna is logged in, they can change 
the logo at the app hub listing page here: 

https://apps.dhis2.org/user/app/de19ff76-3459-4ec1-a881-5b8644cd6c51

Brianna can also invite other people to manage the app 
by going to the crosscut organization and clicking the invite 
member button here: 

https://apps.dhis2.org/user/organisation/a6ca314f-62be-47ac-8a1e-083e90709523

**Comment by briannapoulos** [comment]
<img width="425" alt="Screenshot 2024-01-25 at 2 29 07 PM" src="https://github.com/crosscutio/dhis2-crosscut-app/assets/13878539/2ecc702c-47ea-4254-9878-92259816c737">

@coitemanuel Is this the logo you want on DHIS2?

**Comment by coitemanuel** [comment]
Let's use this color one. : ![Logomark-Color-400](https://github.com/crosscutio/dhis2-crosscut-app/assets/74914430/f7681785-39bb-4f6f-8ff1-9a975366b75c)

**Comment by briannapoulos** [comment]
Updated: 

![Image](https://github.com/crosscutio/dhis2-crosscut-app/assets/13878539/acec7134-7091-4515-9acc-2caed3aa4a56)
