### ISSUE TITLE
Catchment areas not visible in DHIS2 app.

### ISSUE THREAD

**Issue by mckinnoj** [crosscutio/dhis2-crosscut-app#67]
My catchment areas don't appear to be visible when I log into the DHIS2 app:
![image](https://github.com/crosscutio/goals/assets/10966330/287e8379-0b3b-4467-83fb-f398186ad87c)

**Comment by briannapoulos** [comment]
Catchments are now visible:

<img width="2557" alt="Screenshot 2024-10-28 at 2 35 32 PM" src="https://github.com/user-attachments/assets/c41cd119-a75a-470b-a3f5-2b9fe0b21fd2">
